### PR TITLE
leading P not any P

### PR DESCRIPTION
**Pull request by sosodev**

### CODE REVIEW

**Comment by sosodev** [comment]
thanks @ccoVeille for pointing out my mistake

**Comment by sosodev** [comment]
Oh I should have ran the tests before merging... Not enough caffeine.

**Comment by ccoVeille** [comment]
> Oh I should have ran the tests before merging... Not enough caffeine. 

I would say you should have GitHub CI to prevent you merging it. But I'll help with #7

**Comment by sosodev** [comment]
Indeed I should. :)

**Pull request merged**
