### PR TITLE
GitHub action (#10): Add golangci-lint action

### LINKED ISSUE #11: Please consider adding GitHub actions
I'm thinking about

- launching test
- launching golangci-lint
- checking typos
- dependabot (mostly for keeping the GitHub actions up to date)

### LINKED ISSUE #12: Add golang-ci-lint action

### PR DESCRIPTION
**Pull request by ccoVeille**
Fixes #12

### CODE REVIEW

**Comment by ccoVeille** [comment]
I've added the golangci with no rules, we can use a bunch of rules I'm using if needed

**Comment by sosodev** [comment]
Seems reasonable. Did you copy this configuration from another project? It seems quite extensive for this small module.

**Comment by ccoVeille** [comment]
> Seems reasonable. Did you copy this configuration from another project? It seems quite extensive for this small module.

I have a local version of golangci.yaml I maintain for the various projects I work on.

I should publish my dot files at some points

**Review by sosodev — APPROVED** [review]

**Comment by sosodev** [comment]
Thanks for contributing this :)

**Pull request merged**
